### ISSUE TITLE
Mirror folder structure

### ISSUE THREAD

**Issue by crazy4groovy** [d0whc3r/node-s3#131]
**Describe the bug**

When I run this command to mirror a folder structure on my server into S3:

`npx @d0whc3r/node-s3 -e https://s3.us-east-1.amazonaws.com --bucket mybucketname -b * -f /`

All the files nested deep under subfolders are "flattened" into the S3 bucket root, instead of keeping their folder structures.

**To Reproduce**

1. `npx @d0whc3r/node-s3 -e https://s3.us-east-1.amazonaws.com --bucket mybucketname -b * -f /`
2. See files all in root of bucket.

**Expected behavior**

I expect the subfolder structure to remain for all the files in the S3 bucket.

**Screenshots**

**Additional context**

Perhaps an issue with the globbing:
https://github.com/d0whc3r/node-s3/blob/master/src/s3/files.ts#L120

Or the basename stripping:
https://github.com/d0whc3r/node-s3/blob/master/src/s3/files.ts#L70
(Shouldn't the key have the directory folder in it?)

**Comment by d0whc3r** [comment]
Ok, I will check it ASAP
If you have any changes for this fix, create a pr

**Comment by crazy4groovy** [comment]
BTW -- after a few minor code mods, this tool was perfect for helping me migrate a large file archive off of an old ssh server into S3. Thanks!

**Comment by d0whc3r** [comment]
Can you share any of that mods? or any idea to improve the tool?
Thank you very much
